from django.urls import path

from . import views

app_name='bms'
urlpatterns = [
	path('', views.index, name='index'),
	path('itemgroupmaster/', views.itemgroup, name='itemgroup'),
	path('itemgroupmasterview/', views.itemgroupview, name='itemgroupview'),
	path('itemmaster/', views.items, name='items'),
	path('itemmasterview/', views.itemsview, name='itemsview'),
	path('lorrymaster/', views.lorry, name='lorry'),
	path('lorrymasterview/', views.lorryview, name='lorryview'),
	path('businesspartnermaster/', views.bp, name='bp'),
	path('businesspartnermasterview/', views.bpview, name='bpview'),
	path('statemaster/', views.state, name='state'),
	path('sitemaster/', views.sitemaster, name='sitemaster'),
	path('sitemasterview/', views.sitemasterview, name='sitemasterview'),
	path('businessgroupmaster/', views.businessgroup, name='businessgroup'),
	path('businessgroupmasterview/', views.businessgroupview, name='businessgroupview'),
	path('uom/', views.uom, name='uom'),
	path('uomview/', views.uomview, name='uomview'),
	path('quote/', views.quote, name='quote'),
	path('quoteview/', views.quoteview, name='quoteview'),
	path('quotedetails/', views.quotedetails, name='quotedetails'),
	path('quotedetailsview/', views.quotedetailsview, name='quotedetailsview'),
	path('companymaster/',views.companymaster, name='companymaster'),
	path('companymasterview/',views.companymasterview, name='companymasterview'),
	path('html_to_pdf_view/',views.html_to_pdf_view, name='html_to_pdf_view'),
	path('transaction/', views.transact, name='transact'),
	path('transactionview/', views.transactview, name='transactview'),
	path('export_transactions_csv/', views.export_transactions_csv, name='export_transactions_csv'),
   	path('itdelete/<pk>', views.itdelete, name='itdelete'),
   	path('itgrdelete/<pk>', views.itgrdelete, name='itgrdelete'),
	path('lorrydelete/<pk>', views.lorrydelete, name='lorrydelete'),
	path('bdelete/<pk>', views.bdelete, name='bdelete'),
	path('sitedelete/<pk>', views.sitedelete, name='sitedelete'),
	path('bgroupdelete/<pk>', views.bgroupdelete, name='bgroupdelete'),
	path('uomdelete/<pk>', views.uomdelete, name='uomdelete'),
	path('quotedelete/<pk>', views.quotedelete, name='quotedelete'),
	path('quotedetailsdelete/<pk>', views.quotedetailsdelete, name='quotedetailsdelete'),
	path('companydelete/<pk>',views.companydelete, name='companydelete'),
	path('tdelete/<pk>', views.tdelete, name='tdelete'),
]
