# Generated by Django 2.0.7 on 2018-08-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGroupMaster',
            fields=[
                ('group_code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Business Group')),
                ('group_name', models.CharField(max_length=45, verbose_name='Group Name')),
                ('group_head', models.CharField(max_length=30, verbose_name='Group Head')),
                ('contact_no', models.CharField(max_length=15, verbose_name='Contact')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPartnerMaster',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Full name')),
                ('code', models.CharField(max_length=6, null=True, verbose_name='Code')),
                ('address_1', models.CharField(max_length=50, null=True, verbose_name='Address line 1')),
                ('address_2', models.CharField(max_length=50, null=True, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=15, null=True, verbose_name='City')),
                ('pin', models.CharField(max_length=6, null=True, verbose_name='ZIP / Postal code')),
                ('state_code', models.CharField(max_length=2, null=True, verbose_name='State Code')),
                ('gst_no', models.CharField(max_length=15, null=True, verbose_name='GST Number')),
                ('pan_aadhar_no', models.CharField(max_length=16, null=True, verbose_name='PAN / Aadhar Number')),
                ('bp_type', models.CharField(max_length=10, null=True, verbose_name='Business Partner Type')),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroupMaster',
            fields=[
                ('item_group', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Item Group Code')),
                ('item_group_name', models.CharField(max_length=6, verbose_name='Item Group Name')),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GST Rate')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('short_name', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Short Name')),
                ('item_name', models.CharField(max_length=30, verbose_name='Item Name')),
                ('unit_measure', models.CharField(max_length=6, verbose_name='Unit of Measure')),
                ('item_group', models.CharField(max_length=3, verbose_name='Item Group Code')),
            ],
        ),
        migrations.CreateModel(
            name='LorryMaster',
            fields=[
                ('lorry_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Lorry Code')),
                ('lorry_no', models.CharField(max_length=14, verbose_name='Lorry Number')),
                ('driver', models.CharField(max_length=30, verbose_name='Driver Name')),
                ('contact', models.CharField(max_length=15, verbose_name='Contact')),
                ('tax_date', models.DateField(verbose_name="Tax Date: Enter in format 'Year(xxxx)-Month(xx)-Day(xx)'")),
                ('puc_date', models.DateField(verbose_name="PUC Date: Enter in format 'Year(xxxx)-Month(xx)-Day(xx)'")),
                ('permit_date', models.DateField(verbose_name="Permit Date: Enter in format 'Year(xxxx)-Month(xx)-Day(xx)'")),
                ('insur_date', models.DateField(verbose_name="Insurance Date: Enter in format 'Year(xxxx)-Month(xx)-Day(xx)'")),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Length of Lorry')),
                ('breadth', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Breadth of Lorry')),
            ],
        ),
        migrations.CreateModel(
            name='SiteMaster',
            fields=[
                ('site_code', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Site Code')),
                ('site_name', models.CharField(max_length=35, verbose_name='Site Name')),
                ('address_1', models.CharField(max_length=45, verbose_name='Address line 1')),
                ('address_2', models.CharField(max_length=45, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=15, verbose_name='City')),
                ('state_code', models.CharField(max_length=2, null=True, verbose_name='State Code')),
                ('gst_no', models.CharField(max_length=15, verbose_name='GST Number')),
                ('contact_person', models.CharField(max_length=30, verbose_name='Contact Person')),
                ('site_contact', models.CharField(max_length=15, verbose_name='Site Contact')),
            ],
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('state_code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='State Code')),
                ('state_no', models.IntegerField(verbose_name='State Number')),
                ('state_name', models.CharField(max_length=30, verbose_name='State Name')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tr_date', models.DateField(verbose_name="Transaction Date: Enter in format 'Year(xxxx)-Month(xx)-Day(xx)'")),
                ('vr_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Voucher Number')),
                ('lorry_code', models.CharField(max_length=6, null=True, verbose_name='Lorry Code')),
                ('trip', models.IntegerField(null=True, verbose_name='Number of trips')),
                ('challan_no', models.CharField(max_length=20, null=True, verbose_name='Challan Number')),
                ('buyer', models.CharField(max_length=50, null=True, verbose_name='Buyer Name')),
                ('seller', models.CharField(max_length=50, null=True, verbose_name='Seller Name')),
                ('site_code', models.CharField(max_length=7, null=True, verbose_name='Site Code')),
                ('short_name', models.CharField(max_length=6, null=True, verbose_name='Short Name')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Length of Lorry')),
                ('breadth', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Breadth of Lorry')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Height of Item')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Quantity of Item')),
                ('pur_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Pur Rate of Item')),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Sale Rate of Item')),
            ],
        ),
    ]
