# Generated by Django 2.1.1 on 2018-09-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tr_date',
            field=models.DateTimeField(verbose_name="Transaction Date 'Year(xxxx)-Month(xx)-Day(xx)'"),
        ),
    ]
