# Generated by Django 2.1.1 on 2018-09-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0002_auto_20180916_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tr_date',
            field=models.DateField(verbose_name='Transaction Date'),
        ),
    ]
