# Generated by Django 2.1.1 on 2018-09-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0003_auto_20180916_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['tr_date']},
        ),
    ]
