# Generated by Django 2.1.1 on 2018-09-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0006_auto_20180917_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-tr_date', '-vr_no']},
        ),
    ]
