# Generated by Django 2.1.1 on 2018-09-18 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0008_auto_20180919_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='vr_no',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
