# Generated by Django 2.1.1 on 2018-10-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0015_auto_20180919_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('company_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Company Code')),
                ('comp_name', models.CharField(max_length=50, verbose_name='Company Name')),
                ('address_1', models.CharField(max_length=50, verbose_name='Address 1')),
                ('address_2', models.CharField(max_length=50, verbose_name='Address 2')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('pin', models.CharField(max_length=6, verbose_name='Pincode')),
                ('state_code', models.CharField(max_length=2, null=True, verbose_name='State Code')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile')),
                ('gst_no', models.CharField(max_length=15, verbose_name='GST Number')),
                ('pan_no', models.CharField(max_length=10, verbose_name='PAN Number')),
                ('bank_name', models.CharField(max_length=50, verbose_name='Bank Name')),
                ('ac_no', models.CharField(max_length=20, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(max_length=11, verbose_name='IFSC Code')),
                ('jurisdiction', models.CharField(max_length=15, verbose_name='Jurisdiction')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Interest Rate')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quot_no', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Quotation Number')),
                ('quot_dt', models.DateField(verbose_name='Quotation Date')),
                ('frm_dt', models.DateField(verbose_name='From Date')),
                ('to_dt', models.DateField(verbose_name='To Date')),
                ('buyer_code', models.CharField(max_length=8, null=True, verbose_name='Buyer Code')),
                ('group_code', models.CharField(max_length=3, verbose_name='Business Group')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationDetails',
            fields=[
                ('quot_no', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Quotation Number')),
                ('site_code', models.CharField(max_length=7, verbose_name='Site Code')),
                ('short_name', models.CharField(max_length=6, verbose_name='Item Short Name')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rate of Item')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasureMaster',
            fields=[
                ('uom_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='UOM Code')),
                ('uom_name', models.CharField(max_length=35, verbose_name='UOM Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller',
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='pin',
            field=models.CharField(max_length=6, null=True, verbose_name='ZIP / Postal code'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='supplier',
            field=models.CharField(max_length=50, null=True, verbose_name='Supplier Name'),
        ),
        migrations.AlterField(
            model_name='businesspartnermaster',
            name='code',
            field=models.CharField(max_length=8, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='unit_measure',
            field=models.CharField(max_length=8, verbose_name='Unit Of Measure'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Quantity of Item'),
        ),
    ]
