# Generated by Django 2.1.1 on 2018-10-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0018_auto_20181004_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='buyer_code',
            field=models.CharField(max_length=50, null=True, verbose_name='Buyer Code'),
        ),
    ]
